# Experiment 005: mxbai for mechanisms - test longer text embeddings
# =====================================================================

_base: "../base_config.yaml"

experiment:
  name: "exp_005_mxbai_mechanisms"
  description: "mxbai-embed-large for mechanisms only (1024-dim), nomic for interventions/conditions, temperature=0.0"
  tags:
    - mxbai
    - mechanisms_only
    - temperature_0.0

embedding:
  mechanisms:
    model: "mxbai-embed-large"
    dimension: 1024
    batch_size: 5  # Slower model, smaller batches

naming:
  llm:
    temperature: 0.0
