# Experiment 015: Distance Threshold 0.5 - Conditions
# =====================================================

_base: "../base_config.yaml"

experiment:
  name: "threshold_0.5_conditions"
  description: "Test distance_threshold=0.5 for condition clustering (current default baseline)"
  tags:
    - threshold_experiment
    - hierarchical
    - conditions
    - threshold_0.5
    - baseline

clustering:
  # Keep interventions as HDBSCAN (not testing)
  interventions:
    algorithm: "hdbscan"
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"

  conditions:
    algorithm: "hierarchical"
    linkage: "ward"
    distance_threshold: 0.5
    n_clusters: null
    metric: "euclidean"

  mechanisms:
    algorithm: "hdbscan"
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"

naming:
  llm:
    temperature: 0.0
