# Experiment 016: Distance Threshold 0.6 - Conditions
# =====================================================

_base: "../base_config.yaml"

experiment:
  name: "threshold_0.6_conditions"
  description: "Test distance_threshold=0.6 for condition clustering (moderate loosening)"
  tags:
    - threshold_experiment
    - hierarchical
    - conditions
    - threshold_0.6

clustering:
  # Keep interventions as HDBSCAN (not testing)
  interventions:
    algorithm: "hdbscan"
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"

  conditions:
    algorithm: "hierarchical"
    linkage: "ward"
    distance_threshold: 0.6
    n_clusters: null
    metric: "euclidean"

  mechanisms:
    algorithm: "hdbscan"
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"

naming:
  llm:
    temperature: 0.0
