# Experiment 002: Temperature 0.2 - slightly creative
# ====================================================

_base: "../base_config.yaml"

experiment:
  name: "exp_002_temp02"
  description: "nomic-embed-text + HDBSCAN(min_size=2) + temperature=0.2 (slightly creative)"
  tags:
    - temperature_0.2
    - nomic
    - hdbscan

naming:
  llm:
    temperature: 0.2
