# Experiment 012: Distance Threshold 0.6 - Interventions
# ========================================================

_base: "../base_config.yaml"

experiment:
  name: "threshold_0.6_interventions"
  description: "Test distance_threshold=0.6 for intervention clustering (moderate loosening)"
  tags:
    - threshold_experiment
    - hierarchical
    - interventions
    - threshold_0.6

clustering:
  interventions:
    algorithm: "hierarchical"
    linkage: "ward"
    distance_threshold: 0.6
    n_clusters: null
    metric: "euclidean"

  # Keep other entity types as HDBSCAN (not testing yet)
  conditions:
    algorithm: "hdbscan"
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"

  mechanisms:
    algorithm: "hdbscan"
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"

naming:
  llm:
    temperature: 0.0
