# Experiment 021: Distance Threshold 0.7 - Mechanisms
# =====================================================

_base: "../base_config.yaml"

experiment:
  name: "threshold_0.7_mechanisms"
  description: "Test distance_threshold=0.7 for mechanism clustering (looser grouping)"
  tags:
    - threshold_experiment
    - hierarchical
    - mechanisms
    - threshold_0.7

clustering:
  # Keep interventions/conditions as HDBSCAN (not testing)
  interventions:
    algorithm: "hdbscan"
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"

  conditions:
    algorithm: "hdbscan"
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"

  mechanisms:
    algorithm: "hierarchical"
    linkage: "ward"
    distance_threshold: 0.7
    n_clusters: null
    metric: "euclidean"

naming:
  llm:
    temperature: 0.0
