# Experiment 001: Baseline - nomic + HDBSCAN + temperature=0.0
# ==============================================================

_base: "../base_config.yaml"

experiment:
  name: "exp_001_baseline_temp00"
  description: "Baseline: nomic-embed-text + HDBSCAN(min_size=2) + temperature=0.0 (deterministic)"
  tags:
    - baseline
    - temperature_0.0
    - nomic
    - hdbscan

naming:
  llm:
    temperature: 0.0
