# Group-Based Categorization Experiment Configuration

# LLM Settings
llm:
  model: "qwen3:14b"
  base_url: "http://localhost:11434"
  temperature: 0.3
  max_tokens: 2000
  timeout: 60
  max_retries: 3
  retry_delay: 2.0

# Batch Processing
batch_size: 20  # Groups per LLM call

# Categorization Settings
categorization:
  # Include member names in prompt for context
  include_member_names: true
  max_members_in_prompt: 10  # Limit to avoid token overflow

  # Confidence threshold for manual review
  low_confidence_threshold: 0.7

  # Orphan handling
  orphan_categorization_batch_size: 20

# Validation
validation:
  target_coverage: 1.0  # 100% interventions must have categories
  target_orphan_rate: 0.05  # <5% orphans acceptable
  target_agreement_rate: 0.95  # >95% agreement with existing categories

# Experiment Settings
experiment:
  subset_size: 200  # Number of interventions for initial test
  random_seed: 42

# Logging
logging:
  level: "INFO"
  output_dir: "back_end/src/experimentation/group_categorization/results"
