# Base Configuration for Unified Phase 3 Pipeline
# =================================================

# Database paths
database:
  db_path: "c:/Users/samis/Desktop/MyBiome/back_end/data/processed/intervention_research.db"

# Cache directories
cache:
  base_dir: "c:/Users/samis/Desktop/MyBiome/back_end/data/semantic_normalization_cache"
  embeddings_dir: "embeddings"
  clusters_dir: "clusters"
  naming_dir: "naming"

# Phase 3a: Semantic Embedding
embedding:
  # Intervention embeddings
  interventions:
    model: "mxbai-embed-large"
    dimension: 1024
    batch_size: 32
    include_context: false  # Include dosage/duration context
    normalization: "l2"     # l2 or unit_sphere

  # Condition embeddings
  conditions:
    model: "mxbai-embed-large"
    dimension: 1024
    batch_size: 32
    include_context: false  # Include symptom context
    normalization: "l2"

  # Mechanism embeddings
  mechanisms:
    model: "mxbai-embed-large"
    dimension: 1024
    batch_size: 10             # Smaller for longer texts
    include_context: false     # Include intervention/condition context
    normalization: "l2"

# Phase 3b: Clustering
clustering:
  # Intervention clustering
  interventions:
    algorithm: "hierarchical"  # hdbscan or hierarchical
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"
    # Hierarchical-specific (if algorithm=hierarchical)
    linkage: "ward"
    distance_threshold: 0.7    # Optimal threshold from experiments (0.4-0.8)
    n_clusters: null

  # Condition clustering
  conditions:
    algorithm: "hierarchical"  # Optimal: hierarchical with 0.7
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"
    linkage: "ward"
    distance_threshold: 0.7    # Optimal threshold from experiments
    n_clusters: null

  # Mechanism clustering
  mechanisms:
    algorithm: "hierarchical"  # Optimal: hierarchical with 0.7
    min_cluster_size: 2
    min_samples: 1
    cluster_selection_epsilon: 0.0
    metric: "euclidean"
    linkage: "ward"
    distance_threshold: 0.7    # Optimal threshold from experiments
    n_clusters: null

# Phase 3c: LLM Naming
naming:
  llm:
    model: "qwen3:14b"
    base_url: "http://localhost:11434"
    temperature: 0.2          # Optimal from experiments: best naming quality + speed
    max_tokens: 2000
    timeout: null             # No timeout - let LLM take as long as needed
    max_retries: 3
    strip_think_tags: true

  # Prompt configuration
  prompts:
    max_members_shown: 10     # Top N members to show in prompt
    include_frequency: true   # Show paper frequency
    batch_size: 20            # Clusters per LLM call

  # Output validation
  validation:
    min_name_length: 3
    max_name_length: 100

  # Dynamic category discovery
  dynamic_categories:
    enabled: true
    max_categories: 30
    min_usage_for_persistence: 2
    example_categories:
      intervention: [supplement, exercise, medication, gene_therapy]
      condition: [cardiac, neurological, endocrine, oncological]
    forbidden_terms: [treatment, intervention, therapy_general, supplements_general, drug, medicine_general]

  # Category consolidation (Stage 3c.2)
  consolidation:
    enabled: true
    llm_temperature: 0.0  # Conservative (deterministic) for safety
    similarity_threshold: 0.85
    min_group_size: 1  # Always consolidate when possible
    max_consolidation_ratio: 0.5
    timeout: null  # No timeout - let LLM take as long as needed

# Phase 3d: Hierarchical Cluster Merging (EXPERIMENTAL)
phase3d:
  enabled: false  # Not yet fully implemented - set to true to enable
  embedding_dimension: 1024

  # Stage 1: Centroid computation
  centroid:
    normalize: true
    method: "mean"  # mean or median

  # Stage 2: Merge candidate generation
  candidate_generation:
    top_k: 10  # Top K most similar clusters per cluster
    similarity_threshold: 0.6
    max_candidates: 1000

  # Stage 3: LLM validation
  llm_validation:
    model: "qwen3:14b"
    base_url: "http://localhost:11434"
    temperature: 0.0  # Conservative for validation
    timeout: null
    batch_size: 10

  # Stage 4-5: Hierarchy construction
  hierarchy:
    max_depth: 4  # Max hierarchy levels (grandparent → parent → child)
    min_cluster_size_for_merge: 2
    allow_cross_category_merges: true  # Enable functional grouping

# Performance settings
performance:
  parallel_embedding: false   # Use multiprocessing for embedding
  parallel_clustering: false  # Run entity types in parallel
  cache_aggressive: true      # Cache everything possible

# Logging
logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR
  file: "unified_phase3.log"
  console: true
